import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/home');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('admin@gmail.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('password');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Tariffs' }).click();
  await page.getByRole('button', { name: 'Add Block' }).click();
  await page.getByRole('textbox', { name: 'e.g. Block' }).click();
  await page.getByRole('textbox', { name: 'e.g. Block' }).fill('');
  await page.getByRole('textbox', { name: 'e.g. Block' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Block' }).fill('B');
  await page.getByRole('textbox', { name: 'e.g. Block' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g. Block' }).fill('Block 5');
  await page.getByPlaceholder('0', { exact: true }).click();
  await page.getByPlaceholder('0', { exact: true }).fill('1');
  await page.getByPlaceholder('0', { exact: true }).click();
  await page.getByPlaceholder('0', { exact: true }).fill('12');
  await page.getByPlaceholder('0', { exact: true }).click();
  await page.getByPlaceholder('0', { exact: true }).fill('121');
  await page.getByPlaceholder('Unlimited').click();
  await page.getByPlaceholder('Unlimited').fill('150');
  await page.locator('input[name="unitRate"]').click();
  await page.locator('input[name="unitRate"]').fill('1');
  await page.locator('input[name="unitRate"]').click();
  await page.locator('input[name="unitRate"]').fill('18');
  await page.locator('input[name="fixedCharge"]').click();
  await page.locator('input[name="fixedCharge"]').fill('5');
  await page.locator('input[name="fixedCharge"]').click();
  await page.locator('input[name="fixedCharge"]').fill('50');
  await page.locator('input[name="fixedCharge"]').click();
  await page.locator('input[name="fixedCharge"]').fill('500');
  await page.getByRole('button', { name: 'Create Block' }).click();
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('button', { name: 'Delete' }).nth(4).click();
  await page.getByText('Delete', { exact: true }).click();
});